name: Protect package*.json

on:
  pull_request_target:
    branches: [ main ]

jobs:
  prevent-file-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prevent file from being modified
        uses: xalvarez/prevent-file-change-action@v3.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .*package.*.json
